syntax = "proto2";

package remote;

// Whitelist for visualizations, used to apply per-client filtering before sending.
// The filter shouldn't fully hide visualizations. At least their id still has to be be included let the client see the whole hierarchy.
message VisualizationFilter {
    // An entry in the VisualizationFilter whitelist.
    // (0, 1): Vis 1 in source 0
    // (None, 1): Vis 1 from any source
    // (0, None): All visualizations from source 0
    // (None, None): All visualizations
    message VisualizationFilterEntry {
        optional uint32 source_id = 1;
        optional uint32 vis_id = 2;
    }

    repeated VisualizationFilterEntry allowed_visualizations = 1;
}

// Manually moves a robot to the specified location until a different command is issued.
// This means you have to send an empty command after finishing to hand control back over to the ai.
message RobotMoveCommand {
    required uint32 robot_id = 1;
    required bool is_blue = 2;
    optional float p_x = 3;
    optional float p_y = 4;
}
