[package]
name = "xrvis-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
3d-panels = []

[dependencies]
bevy = { workspace = true, features = ["bevy_feathers"] }
derive_more = { workspace = true, features = ["into_iterator"] }
lucide-icons.workspace = true

sslgame.workspace = true
